name: hola mundo
on:
  push:
    branches: master
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
    - name: error out
      run: |
        echo esto debe fallar
        erroringOut
    - name: hola mundo
      run: docker build .
